name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create API gateway env
        run: echo "${{ secrets.API_GATEWAY_ENV }}" > ./api-gateway/.env.prod

      - name: Create Identity service env
        run: echo "${{ secrets.IDENTITY_SERVICE_ENV }}" > ./identity-service/.env.prod

      - name: Create Post service env
        run: echo "${{ secrets.POST_SERVICE_ENV }}" > ./post-service/.env.prod

      - name: Create Media service env
        run: echo "${{ secrets.MEDIA_SERVICE_ENV }}" > ./media-service/.env.prod

      - name: Create Search service env
        run: echo "${{ secrets.SEARCH_SERVICE_ENV }}" > ./search-service/.env.prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add VPS SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 142.93.162.34 >> ~/.ssh/known_hosts

      - name: Set up SSH key for authentication
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 142.93.162.34
          username: root
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/var/projects/socialNetMicroservices
            git pull origin main
            docker-compose down
            docker-compose up -d

      - name: Debug SSH connection (optional)
        run: |
          ssh -v -i ~/.ssh/id_rsa root@142.93.162.34 "echo 'SSH connection successful'"
        continue-on-error: true
